// Generated by Haxe 4.2.2
(function ($global) { "use strict";
var MyClass = function() { };
MyClass.method = function() {
};
var Main = function() { };
Main.main = function() {
	var ret = 5060;
	console.log("Main.hx:87:",ret);
};
var MyAbstract = {};
MyAbstract._new = function(i) {
	var this1 = i;
	return this1;
};
MyAbstract.extendDoc = function(this1) {
	return "Integer";
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
MyClass.__meta__ = { obj : { author : ["Sunshuai"]}, statics : { method : { broken : [false]}}, fields : { value : { range : [1,8]}}};
Main.main();
})({});
